[package]
name = "wasm-webpack-template"
version = "0.1.0"
edition = "2021"

[lib]
name = "index"
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0.166", features = ['derive'] }
tsify = { version = "0.4.5", features = ["js"] }
wasm-bindgen = "0.2.87"